# Generated by Django 4.2 on 2023-04-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('setup', models.TextField(verbose_name='Установка')),
                ('time', models.TextField(verbose_name='Время')),
                ('task', models.TextField(verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Запись на прибор',
                'verbose_name_plural': 'Записи на приборы',
            },
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
