# Generated by Django 4.2 on 2023-04-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_reg_alter_task_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Del',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Введите номер записи')),
            ],
        ),
    ]
