# Generated by Django 4.2 on 2023-05-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_del'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Del',
        ),
        migrations.AddField(
            model_name='task',
            name='cur_time',
            field=models.TextField(null=True, verbose_name='Время добавления'),
        ),
    ]
