# Generated by Django 4.2 on 2023-05-02 12:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_del_task_cur_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='cur_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='task',
            name='cur_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
